### ISSUE TITLE
Using xule within a Python script

### ISSUE THREAD

**Issue by micmalti** [xbrlus/xule#6]
Hi, I wish to use xule to extract pertinent data from SEC 10-Q filings but I'm not finding any documentation on how to do so strictly within Python. Is it possible, given that this project is written in Python?

**Comment by davidtauriello** [comment]
Hi @micmalti - check out https://xbrl.us/xule linked in the about detail for this repository - documentation for the spec is posted in the sidebar there.

**Comment by davidtauriello** [comment]
Hi @micmalti - apologies, as I should have also referenced an issue in this repository. See #5
