### ISSUE TITLE
Inconsistent `.role-description` value when getting taxonomy using `taxonomy(...)`

### ISSUE THREAD

**Issue by selgamal** [xbrlus/xule#8]
**_Edited_**

This may be a trival issue or I am doing something wrong, I am not getting the correct value for property `networks().role-description` (or `role.description`) if a taxonomy is loaded using `taxonomy(<taxonomy_url>)`.

I am trying to use XULE to compare 2 taxonomies, I am loading a taxonomy using `arelleCmdLine -f <loaded_taxonoy_url>` and then the XULE rule gets the other taxonomy for comparison using  `taxonomy(<other_taxonomy_url>)`. It appears that when trying to get the value of property `networks().role-description` (or `role.description`) for a specific role uri form both taxonomies, the result is always returned from the taxonomy that was loaded first.

To demonstrate, consider ESEF taxonomy 2021 which has a new role `http://www.esma.europa.eu/xbrl/role/all/ifrs_17_role-836600o`, this role does not exist in ESEF taxonomy 2019, if I load ESEF taxonomy 2019 first using:

    arelleCmdLine -f http://www.esma.europa.eu/taxonomy/2019-03-27/esef_all.xsd ...

Then try to get the `role-description` property based on ESEF 2021 loaded later in the rule using `taxonomy(...)` , I get a `none` value while there should be a description for this role in ESEF 2021 taxonomy, this is the rule I am using:
```java
output 
list(taxonomy("http://www.esma.europa.eu/taxonomy/2021-03-24/esef_all.xsd")
        .networks(none, "http://www.esma.europa.eu/xbrl/role/all/ifrs_17_role-836600o")
        .role-description) /* This returns None, while should return [836600o] Notes - Insurance contracts (IFRS 17) */
```
Load **ESEF 2019** first and run above rule using:
```
$ arelleCmdLine --plugins xule -f http://www.esma.europa.eu/taxonomy/2019-03-27/esef_all.xsd --internetRecheck never --xule-run --xule-compile link-role-test.xule --xule-rule-set link-role-test.xule.zip --logFormat "%(message)s"
```
The expected result is ` [836600o] Notes - Insurance contracts (IFRS 17)` but the result I am getting:
```bash
set(None)
```

Now if I load ESEF 2021 first and run the same exact rule using:
```bash
$ arelleCmdLine --plugins xule -f http://www.esma.europa.eu/taxonomy/2021-03-24/esef_all.xsd --internetRecheck never --xule-run --xule-compile link-role-test.xule --xule-rule-set link-role-test.xule.zip --logFormat "%(message)s"
```

We get the correct result Result:
```bash
set([836600o] Notes - Insurance contracts (IFRS 17))
```

If I am not mistaken the results for calling role-description should be consistent no matter which taxonomy gets loaded first, unless I am missing something...

**Comment by campbellpryde** [comment]
Your code is correct.  There seems to be an issue with the underlying data
model of Arelle, which seems to be dropping the used-on and description
attributes of this and a few other roles in certain circumstances.  We are
looking into the issue and hope to resolve asap.

Campbell Pryde

President and CEO

XBRL US Inc.


***@***.*** ***@***.***>*

*https://xbrl.us <https://xbrl.us>*

+ 1 (917) 582-6159 (Mobile)


[image: XBRL US]

The non-profit community <https://xbrl.us/xusmembers> improving U.S.
reporting through a free, open standard
<https://xbrl.us/home/learn/free-open-standards/>.

**Comment by campbellpryde** [comment]
Your code is correct.  There seems to be an issue with the underlying data model of Arelle, which seems to be dropping the used-on and description attributes of this and a few other roles in certain circumstances.  We are looking into the issue and hope to resolve asap.

**Comment by campbellpryde** [comment]
Upon further investigation this seems o be an issue if two taxonomies are being used.  The description from the open taxonomy seems to be used for the description of the second taxonomy where the uri is the same.  In this case the 2019 description and URI used on is none and this is reported for 2021.

**Comment by selgamal** [comment]
> Upon further investigation this seems o be an issue if two taxonomies are being used. The description from the open taxonomy seems to be used for the description of the second taxonomy where the uri is the same. In this case the 2019 description and URI used on is none and this is reported for 2021.

Yes that is the case, I just couldn't pin down which part of the code was responsible for this, but I think I found it, I added a draft pr to explain what I think is happening with the a quick fix.

**Comment by campbellpryde** [comment]
We have updated the original pull request.

**Comment by selgamal** [comment]
Yes 4589881919036a16907417887f31d26c3dfb391c that looks much better then what I sent! 

A last question, is there a function similar to xbrl formula [xfi:linkbase-link-roles](https://specifications.xbrl.org/registries/functions-registry-1.0/90501%20xfi.linkbase-link-roles/90501%20xfi.linkbase-link-roles%20function.html)?

**Comment by campbellpryde** [comment]
You would  do the following if you wanted a set of parent child link roles:
taxonomy().networks(parent-child)
or for a specific taxonomy:
taxonomy('http://www.esma.europa.eu/taxonomy/2019-03-27/esef_all.xsd').networks(parent-child)

**Comment by campbellpryde** [comment]
If you wanted the descriptions of the parent-child arcroles for the 2019 esef you could do the following:

$esef = taxonomy('http://www.esma.europa.eu/taxonomy/2019-03-27/esef_all.xsd');
filter $esef.networks(parent-child) returns $item.role.description

**Comment by selgamal** [comment]
> If you wanted the descriptions of the parent-child arcroles for the 2019 esef you could do the following:
> 
> $esef = taxonomy('http://www.esma.europa.eu/taxonomy/2019-03-27/esef_all.xsd'); filter $esef.networks(parent-child) returns $item.role.description

The `filter...where` is very useful, exactly what I was looking for. Thank you again!
